-- Hand-written migration (not generated by drizzle-kit): partial unique
-- indexes that Drizzle's schema builder cannot express, enforcing
-- PLAN.md §4.2 "max 1 open outgoing / incoming challenge per member" at the
-- database level so a race between two concurrent requests can't create two
-- open challenges for the same member.
--
-- CAVEAT: this hard-codes maxOpenOutgoing = maxOpenIncoming = 1 (the
-- documented default). If an admin ever raises either setting above 1 for a
-- division, these indexes must be replaced by a trigger that counts open
-- rows instead of relying on uniqueness.
CREATE UNIQUE INDEX "challenges_one_open_outgoing_idx"
  ON "challenges" ("challenger_id")
  WHERE "state" NOT IN ('declined', 'cancelled', 'settled');--> statement-breakpoint

CREATE UNIQUE INDEX "challenges_one_open_incoming_idx"
  ON "challenges" ("defender_id")
  WHERE "state" NOT IN ('declined', 'cancelled', 'settled');
